apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-vue-hello-world-backend.fullname" . }}
  labels:
{{- include "spring-vue-hello-world-backend.labels" . | nindent 4 }}
{{ if .Values.service.labels}}
{{- toYaml .Values.service.labels | nindent 4 }}
{{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-vue-hello-world-backend.selectorLabels" . | nindent 4 }}
