apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: spring-vue-hello-world
spec:
  encryptedData:
    .dockerconfigjson: AgCkgWqGAPmjG5aEV/PThpC9cmQ4HVfo3MCLMQE46fvQfiz0pbrqp5kpbWZOIXiMsZ4XbU/OjQ4alJ5XdnFsv5ybWzUNO5SsLpoEGnZxqJdCzsc7wwWm7H4Wuw3z+lJLI7I768+A2wwaDFwtSFWMn0OrGwlogUTCD54RJdbXImA0CQoDaSvtZkqGU7u+F8h6n3MsFcZA7by17Ko+lfFFxJ0/nakYYy4DpcJ7G5NrdYibEYtgQa6fsAn5GRPK0H70WlrCgJhd5ZT853+yCVvt0xJzh7Dt5EXkYR3Di9yjh2n6jXszbEapyO0g1NPGqndyOCuLAb0B0EUHy17Ufo338of17V6I393Pb91RYjbnUHJHivnvVwMEMr7i5hilF4toYTYevk5Zhm0kTMcZaAKOXAEf5loa3ecNXT6Uh5ujG2J5eyByTj4C5PukNA9GAGrz7K25LXGM3Tn0Q33JcTKcBPebcmp2Dl262NgCA3cVGSd2XbtcthPwFyGjMdfTzdP+mTfcMF7CjOlzcMjzhjs9/hfVSi8tVRXvBOXelzA7dcBfVJcBLnypJ/pSpRoz0HpvvBYOJSbvXmZ80yozm/UfPlei0Ydlx35mmL/xeQST8Eg2nN/vlvw3U9ayjtdsCryJwWnWxaD89jHHp7sM7GGJQrPmC38/Ggm89Afeba1XTbtaZOD+xf+y+Jqj76uIuzjNC6ITFLshekGiX+niECI7gRT5frgVnDiSvbtJxze2Lpx3fIWH/P9gamJki232d89xv63LdGEBqkXXzZ9ugHsb1Pv6j6Wlxl6cCW/86QPoTWrn27eNjCORepwU8v9pUnRe/qR92Qf0hVo7M8+FyNfi1zWTuYyZr7AlFo5FrUbKHV4bZw+5KPlAtxgBSmn7QiPq33jUdKQ7Lbd7xbk/aGHxwEIh69p+0m6xuIQJ374J
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: spring-vue-hello-world
    type: kubernetes.io/dockerconfigjson

